### PR TITLE
Include 'InAccel FPGA Operator' App

### PR DESCRIPTION
**Pull request by eliaskoromilas**
Simplifying FPGA management in KubeSphere

:house: [Homepage](https://inaccel.com)
:pencil: [Source](https://github.com/inaccel/helm)
:link: [Documentation](https://docs.inaccel.com)

> Chart.yaml
```yaml
annotations:
  app.kubesphere.io/category: Infrastructure
  app.kubesphere.io/display-name: InAccel FPGA Operator
...
```

### CODE REVIEW

**Comment by xyz-li** [comment]
Does the fpga-operator just run in the namespace kube-system?
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "labels" . | nindent 4 }}
  name: {{ .Chart.Name }}
  namespace: kube-system
```

**Comment by eliaskoromilas** [comment]
> Does the fpga-operator just run in the namespace kube-system?

Yes, InAccel FPGA Operator requires elevated privileges in order to manage the FPGAs' lifecycle. As of now, it runs (hard-coded) in the `kube-system` namespace.

In KubeSphere, this can be a problem as it will allow users with access to the App Store to run arbitrary containers in `kube-system`, since the container images of this chart are configurable. An option would be to introduce an `app.kubesphere.io/project` annotation that would enable the app only for deployment on the `kube-system` namespace.

Generally, the FPGA Operator can be considered a **Cluster Tool** installed/updated only by the cluster-admins. However, https://github.com/kubesphere/kubesphere/issues/4231 doesn't allow admins to add 3rd party Helm repos in the `kube-system`'s Workspace. If the App Store is meant for user applications only, I guess at least this issue should be addressed to allow administrators deploy charts that monitor/provision the resources of their clusters.

**Comment by eliaskoromilas** [comment]
I'm closing this in favor of [kubesphere/helm-charts](https://github.com/kubesphere/helm-charts).

**Pull request closed without merging**
